spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/fashion-store
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=fashionstoresecretkeyfashionstoresecretkey
admin.email=admin@fashionstore.com
admin.password=Admin123456Zz@